model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.triplane_trainer.Lifting_3d
  params:

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 100 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.lift3d.UNetLift3d
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 96
        model_channels: 192
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: False
        transformer_depth: 1
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity


data:
  target: ldm.data.objaverse.ObjaverseDataModuleFromConfig
  params:
    root_dir: ''  # The root of rendering data
    batch_size: 72
    num_workers: 16
    total_view: 12
    train:
      validation: False
      image_transforms:
        size: 256

    validation:
      validation: True
      image_transforms:
        size: 256


lightning:
  find_unused_parameters: false
  metrics_over_trainsteps_checkpoint: True
  modelcheckpoint:
    params:
      every_n_train_steps: 5000
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 32
        increase_log_steps: False
        log_first_step: True

  trainer:
    benchmark: True
    val_check_interval: 500
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    max_epochs: 50000
